version: '3.1'
services:
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        depends_on:
            - flask
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - our-network
        ports:
            - 80:80
    flask:
        build:
            context: ./app/
            dockerfile: Dockerfile
        image: py_app
        container_name: py_flask
        networks:
            our-network:
                aliases:
                    - py_flask
        ports:
            - 8080:5000
networks:
    our-network: