version: '3.1'
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx_reverseproxy
        depends_on:
            - flask
        networks:
            - docker-network
        ports:
            - 80:80
    flask:
        build:
            context: ./app/
            dockerfile: Dockerfile
        image: flask:v1
        container_name: flask_webapp
        environment:
            - FLASK_APP=./app/api.py
        command: python ./app/api.py
        networks:
            docker-network:
                aliases:
                    - flask_webapp
        ports:
            - 8080:8080
networks:
    docker-network: