
version: '3'

services:

  flask_app:
   image: py-test:1.0.3
   container_name: flask-app
   ports:
     - 8080:8080
   networks:
     docker-network:
       aliases:
         - flask_webapp

  ngnix:
    build:
      context: ./nginx
      dockerfile: Dockerfile
   image: nginx
   container_name: ngnix
   ports:
     - 80:80
   depends_on:
     - flask-app
networks:
    docker-network: